### ISSUE TITLE
충전기 연결 후 딥슬립시 깨어나지 못하는 문제 발생

### ISSUE THREAD

**Issue by widz4rd** [widz4rd/WIDzard_Kernel_E250_KK#2]
충전기 연결 후 딥슬립시 깨어나지 못하는 문제 발생

**Comment by brightcj** [comment]
저도 잉와 괸련된 문제가 있는것 같습니다. 회면을 꺼두고 슬립시 충전을 하면 기본 잠금화면이 먹통이 도ㅔ거나. 폰이 갑작스레 재부팅되는 현산이일어납니다. Widzard 2.5 shv e250s 사용중입니다.

**Comment by widz4rd** [comment]
폰이 죽지 않고 재부팅이 되던가요?

**Comment by widz4rd** [comment]
해결되었습니다.
