### ISSUE TITLE
충전시 오류

### ISSUE THREAD

**Issue by brightcj** [widz4rd/WIDzard_Kernel_E250_KK#3]
충전을 하다 보면 폰이 재부팅되며. 꺼놓은 상태로 충전을 할시에는 폰이 강제로 집니다. 또, 충전즁에는 가끔 잠금회면이 먹통이되기도 합니다. 위저드 커널 2.5 사용즁이며, shv e250s . Cm12.1 사용중입니다.

**Comment by widz4rd** [comment]
해결되었습니다.
